### ISSUE TITLE
Feedback zur ersten Pflichtübung

### ISSUE THREAD

**Issue by Tubiii** [tpe-lecture/repo-44#1]
<h1>Paket</h1>
Die Paketbenennung ist nicht eindeutig.
[-3 Punkte]

<h1>JavaDoc</h1>
JavaDoc ist in Ordnung.

<h1>Coding-Standard</h1>
Die Sichtbarkeit in Klasse Figur ist nicht entsprechend vorgenommen worden.
[-2 Punkte]
	
<h1>JUnit</h1>
Die Testklasse ist in Ordnung.

<h1>UML</h1>
Konstruktoren aus der Klasse Figur müssen mit # gekennzeichnet sein.
[-2 Punkte]

<h1>Bewertung</h1>
<b>93 Punkte

Bitte korrigieren Sie die genannten Fehler bis zur nächsten Übungsstunde, checken Sie die Verbesserung ein und schließen Sie dann dieses Issue.</b>

**Comment by joernritz** [comment]
Fehler verbessert.
Packetbennenung vorgenommen und Konstruktoren der Klasse Figur Protected.

UML Klassendiagramm wurde auf Papier abgegeben und kann dadruch aktuell nicht verbessert werden.
